### ISSUE TITLE
function BoundBox not defined

### ISSUE THREAD

**Issue by sharooque** [hnikoo/Yolo_object_detection#1]
Hello,
The call to function BoundBox in module yoloutils causes an error as the function BoundBox is not defined.

**Comment by hnikoo** [comment]
@sharooque I pushed a new change. I think I fixed it. take a look.

**Comment by sharooque** [comment]
@hnikoo Thanks a lot for the help !

**Comment by hnikoo** [comment]
@sharooque this is V2. it is possible to have multiple box. you can choose the most likely ones. The model I trained is not perfect. I didn't spend much time on that. you can download better trained models here: https://github.com/experiencor/keras-yolo2 ====> https://drive.google.com/drive/folders/10oym4eL2RxJa0gro26vzXK__TtYOP5Ng . However you need to use the correct architecture for each model.
