### ISSUE TITLE
Enquiry about the model

### ISSUE THREAD

**Issue by coderz97** [hnikoo/Yolo_object_detection#2]
Hey,
May I know how much accuracy this model has?

**Comment by hnikoo** [comment]
@coderz97 I don't actually remember the accuracy of the my trained model. but you can download original models (binaries ) here: https://drive.google.com/drive/folders/10oym4eL2RxJa0gro26vzXK__TtYOP5Ng

accuracy for those models are reported here https://github.com/experiencor/keras-yolo2

**Comment by hnikoo** [comment]
@coderz97 I don't actually remember the accuracy of the my trained model, it was long time a go. but you can download original YOLO models  here: https://drive.google.com/drive/folders/10oym4eL2RxJa0gro26vzXK__TtYOP5Ng

accuracy for those models are reported here https://github.com/experiencor/keras-yolo2

**Comment by coderz97** [comment]
@hnikoo Thankyou!
I was looking for a yolo v2 model trained on imagenet for a project and that's when I came across your model.I could not find any other yolo v2 model that was trained on imagenet. 
So is there any way to find the accuracy?

**Comment by coderz97** [comment]
Thankyou for the help! @hnikoo
